# Generated by Django 3.0.4 on 2020-03-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
